use std::collections::BTreeMap;
use std::path::Path;

#[derive(serde::Deserialize)]
struct IconEntry {
    x: u32,
    y: u32,
    width: u32,
    height: u32,
}

fn main() {
    println!("cargo:rerun-if-changed=resources/icons.json");
    println!("cargo:rerun-if-changed=resources/icons.png");
    println!("cargo:rerun-if-changed=resources/equirect.png");

    build_windows_icon();


    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("icons_data.rs");

    let json_str =
        std::fs::read_to_string("resources/icons.json").expect("resources/icons.json not found");

    let icons: BTreeMap<String, IconEntry> =
        serde_json::from_str(&json_str).expect("failed to parse icons.json");

    // Compute sprite-sheet dimensions from the data.
    let mut sheet_w = 0u32;
    let mut sheet_h = 0u32;
    for v in icons.values() {
        sheet_w = sheet_w.max(v.x + v.width);
        sheet_h = sheet_h.max(v.y + v.height);
    }

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs — do not edit.\n\n");
    out.push_str(&format!(
        "pub const ICONS_SHEET_WIDTH: f32 = {sheet_w}.0;\n"
    ));
    out.push_str(&format!(
        "pub const ICONS_SHEET_HEIGHT: f32 = {sheet_h}.0;\n\n"
    ));
    out.push_str(
        "#[derive(Clone, Copy)]\n\
         pub struct IconSprite { pub x: f32, pub y: f32, pub w: f32, pub h: f32 }\n\n",
    );

    for (name, v) in &icons {
        // Convert JSON key to SCREAMING_SNAKE_CASE Rust identifier.
        let const_name = name.to_uppercase().replace('-', "_");
        out.push_str(&format!(
            "#[allow(dead_code)]\n\
             pub const ICON_{}: IconSprite = IconSprite {{ x: {}.0, y: {}.0, w: {}.0, h: {}.0 }};\n",
            const_name, v.x, v.y, v.width, v.height,
        ));
    }

    std::fs::write(&out_path, out).expect("failed to write icons_data.rs");
}

/// Returns the version label to stamp on large icons.
/// Release builds get `"v1.2.0"`; every other profile gets `"v1.2.0-dev"`.
fn get_version_label() -> String {
    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "?.?.?".to_string());
    let profile = std::env::var("PROFILE").unwrap_or_default();
    if profile == "release" {
        format!("v{version}")
    } else {
        format!("v{version}-dev")
    }
}

/// 3×5 pixel bitmaps for the characters used in version labels.
/// Each `u8` is one row; bits 2..0 map to columns left→right.
fn char_pixels(c: char) -> Option<[u8; 5]> {
    Some(match c {
        '0' => [0b111, 0b101, 0b101, 0b101, 0b111],
        '1' => [0b010, 0b110, 0b010, 0b010, 0b111],
        '2' => [0b111, 0b001, 0b011, 0b100, 0b111],
        '3' => [0b111, 0b001, 0b011, 0b001, 0b111],
        '4' => [0b101, 0b101, 0b111, 0b001, 0b001],
        '5' => [0b111, 0b100, 0b111, 0b001, 0b111],
        '6' => [0b111, 0b100, 0b111, 0b101, 0b111],
        '7' => [0b111, 0b001, 0b001, 0b001, 0b001],
        '8' => [0b111, 0b101, 0b111, 0b101, 0b111],
        '9' => [0b111, 0b101, 0b111, 0b001, 0b111],
        '.' => [0b000, 0b000, 0b000, 0b010, 0b010],
        '-' => [0b000, 0b000, 0b111, 0b000, 0b000],
        'd' => [0b001, 0b001, 0b011, 0b101, 0b011],
        'e' => [0b111, 0b100, 0b111, 0b100, 0b111],
        'v' => [0b101, 0b101, 0b101, 0b010, 0b010],
        _   => return None,
    })
}

/// Stamp `label` in the bottom-left corner of `canvas`.
/// The font is scaled up by `scale` pixels per source pixel.
fn draw_version_label(
    canvas: &mut image::ImageBuffer<image::Rgba<u8>, Vec<u8>>,
    label: &str,
    scale: u32,
) {
    const CHAR_W: u32 = 3;
    const CHAR_H: u32 = 5;
    const SPACING: u32 = 1; // pixels between characters (pre-scale)

    let text_h = CHAR_H * scale;
    let margin = 2 * scale;

    let cw = canvas.width();
    let ch = canvas.height();

    let bg_x = margin;
    let bg_y = ch.saturating_sub(text_h + margin * 3);

    // White text.
    let tx = bg_x + margin;
    let ty = bg_y + margin;
    for (i, c) in label.chars().enumerate() {
        if let Some(bitmap) = char_pixels(c) {
            let cx = tx + i as u32 * (CHAR_W + SPACING) * scale;
            for (row, &bits) in bitmap.iter().enumerate() {
                for col in 0..CHAR_W {
                    if (bits >> (CHAR_W - 1 - col)) & 1 == 1 {
                        for sy in 0..scale {
                            for sx in 0..scale {
                                let px = cx + col * scale + sx;
                                let py = ty + row as u32 * scale + sy;
                                if px < cw && py < ch {
                                    canvas.put_pixel(px, py, image::Rgba([255, 255, 255, 255]));
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

/// Generate a multi-size .ico from resources/equirect.png and embed it into
/// the Windows PE binary via winresource.  On non-Windows targets this is a
/// no-op.
fn build_windows_icon() {
    let out_dir  = std::env::var("OUT_DIR").unwrap();
    let ico_path = Path::new(&out_dir).join("equirect.ico");

    // Build the .ico even on non-Windows so CI catches regressions.
    {
        use image::{imageops::FilterType, DynamicImage, ImageBuffer, Rgba};

        let src_bytes = std::fs::read("resources/equirect.png")
            .expect("resources/equirect.png not found");
        let src: DynamicImage = image::load_from_memory(&src_bytes)
            .expect("failed to decode equirect.png");

        let mut icon_dir = ico::IconDir::new(ico::ResourceType::Icon);

        for size in [16u32, 32, 48, 256, 512] {
            // Fit the logo into a square canvas with transparent letterboxing.
            let sw = src.width();
            let sh = src.height();
            let scale = (size as f64 / sw as f64).min(size as f64 / sh as f64);
            let nw = (sw as f64 * scale).round() as u32;
            let nh = (sh as f64 * scale).round() as u32;

            let resized = src.resize_exact(nw, nh, FilterType::Lanczos3);

            // Paste onto a transparent square.
            let mut canvas: ImageBuffer<Rgba<u8>, Vec<u8>> =
                ImageBuffer::new(size, size);
            let ox = (size - nw) / 2;
            let oy = (size - nh) / 2;
            for (x, y, px) in resized.to_rgba8().enumerate_pixels() {
                canvas.put_pixel(ox + x, oy + y, *px);
            }

            // Stamp the version number on larger sizes where text is legible.
            if size >= 256 {
                let label = get_version_label();
                draw_version_label(&mut canvas, &label, size / 64);
            }

            let img = ico::IconImage::from_rgba_data(size, size, canvas.into_raw());
            icon_dir.add_entry(ico::IconDirEntry::encode(&img).expect("ico encode failed"));
        }

        let ico_file = std::fs::File::create(&ico_path).expect("failed to create equirect.ico");
        icon_dir.write(ico_file).expect("failed to write equirect.ico");
    }

    // Embed the icon into the Windows binary.
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os == "windows" {
        let mut res = winresource::WindowsResource::new();
        res.set_icon(ico_path.to_str().expect("ico path not UTF-8"));
        res.compile().expect("winresource compile failed");
    }
}
