use std::collections::BTreeMap;
use std::path::Path;

#[derive(serde::Deserialize)]
struct IconEntry {
    x: u32,
    y: u32,
    width: u32,
    height: u32,
}

fn main() {
    println!("cargo:rerun-if-changed=resources/icons.json");
    println!("cargo:rerun-if-changed=resources/icons.png");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("icons_data.rs");

    let json_str =
        std::fs::read_to_string("resources/icons.json").expect("resources/icons.json not found");

    let icons: BTreeMap<String, IconEntry> =
        serde_json::from_str(&json_str).expect("failed to parse icons.json");

    // Compute sprite-sheet dimensions from the data.
    let mut sheet_w = 0u32;
    let mut sheet_h = 0u32;
    for v in icons.values() {
        sheet_w = sheet_w.max(v.x + v.width);
        sheet_h = sheet_h.max(v.y + v.height);
    }

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs — do not edit.\n\n");
    out.push_str(&format!(
        "pub const ICONS_SHEET_WIDTH: f32 = {sheet_w}.0;\n"
    ));
    out.push_str(&format!(
        "pub const ICONS_SHEET_HEIGHT: f32 = {sheet_h}.0;\n\n"
    ));
    out.push_str(
        "#[derive(Clone, Copy)]\n\
         pub struct IconSprite { pub x: f32, pub y: f32, pub w: f32, pub h: f32 }\n\n",
    );

    for (name, v) in &icons {
        // Convert JSON key to SCREAMING_SNAKE_CASE Rust identifier.
        let const_name = name.to_uppercase().replace('-', "_");
        out.push_str(&format!(
            "#[allow(dead_code)]\n\
             pub const ICON_{}: IconSprite = IconSprite {{ x: {}.0, y: {}.0, w: {}.0, h: {}.0 }};\n",
            const_name, v.x, v.y, v.width, v.height,
        ));
    }

    std::fs::write(&out_path, out).expect("failed to write icons_data.rs");
}
